# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_stableMarriage_rcpp_hello_world`)
}

stableMatching <- function(list1, list2) {
    .Call(`_stableMarriage_stableMatching`, list1, list2)
}

